sonar.projectKey=vzwingma_gestion-budget-ihm
sonar.projectName=IHM
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=build/**,public/**,**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info