/**
 * Constantes des ID pour le formulaire
 * @type {{INTERCOMPTES: string, INPUT: string, FORM: string, DATE_OPERATION: string, LIBELLE: string, MENSUALITE: string, VALUE: string, CATEGORIE: string}}
 */
export enum OPERATION_EDITION_FORM {
    FORM = "OPERATION_FORM",
    VALUE = "OPERATION_VALUE",
    LIBELLE = "OPERATION_LIBELLE",
    DATE_OPERATION = "OPERATION_DATE_OPERATION",
    MENSUALITE = "OPERATION_MENSUALITE",
    CATEGORIE = "OPERATION_CATEGORIE",
    INTERCOMPTES = "OPERATION_INTERCOMPTES",
    INPUT = "_INPUT",
    FORM_VALIDATION = "FORM_VALIDATION"
}

export const EMPTY_CATEGORIE = {id: null, libelle: "NULL-2"}


